### ISSUE TITLE
新版本一个片段都下载不了

### ISSUE THREAD

**Issue by yimshing** [aklws/youku_spi#2]
报告作者，
无论是release里面的exe版本还是通过git获取代码使用都无法下载

获取集数并下载的按钮按了没有任何反应

D:\TDDOWNLOADS\来自分享\HDR\youku_spi>python main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\TDDOWNLOADS\来自分享\HDR\youku_spi\gui\main_window.py", line 31, in download
    episodes = downloader.download_and_merge(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TDDOWNLOADS\来自分享\HDR\youku_spi\logic\youku_downloader.py", line 42, in download_and_merge
    print(response.json())
          ^^^^^^^^^^^^^^^
  File "D:\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by aklws** [comment]
因为新的解析接口失效了，正在沟通中。。。

**Comment by yimshing** [comment]
有机会修复吗

**Comment by aklws** [comment]
修复了， 是参数过期了。
